### ISSUE TITLE
Moved things around a bit to make it easier to read. The test now makes sure that the overall thing does what it should.

### ISSUE THREAD

**Issue by Tyszek343** [autonomousapps/dependency-analysis-gradle-plugin#1001]
Moved things around a bit to make it easier to read. The test now makes sure that the overall thing does what it should.

_Originally posted by @jjohannes in https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/822#discussion_r1029676573_

**Comment by autonomousapps** [comment]
What are you doing?
