### ISSUE TITLE
The project doesn't work on IntelliJ

### ISSUE THREAD

**Issue by BraisGabin** [autonomousapps/dependency-analysis-gradle-plugin#1015]
IntelliJ fails when I clone the project with the current `main` (1037b3f44d0ce7079f15c978c78780ec07235067)

I get this error message:

```
Could not create task ':testkit:gradle-testkit-plugin:promote'.
Username must not be null
```

I get the same issue when I execute `./gradlew -p testkit promote` but I assume that's correct. But this shouldn't make IntelliJ complain.

**Comment by autonomousapps** [comment]
Thanks for the issue. Could you file one on Intellij to stop configuring all tasks?
