### ISSUE TITLE
Enable `:reason` task to get reason for specific gradle capabilities (e.g. `testFixtures`)

### ISSUE THREAD

**Issue by Nava2** [autonomousapps/dependency-analysis-gradle-plugin#1097]
**Describe the solution you'd like**
Some form of CLI parameters that enables specifying which gradle capability that is cared about. Such that, only that capability is shown. 

For example, 
```
./gradlew :project:reason --id ':other-project' --capability 'com.example:other-project-test-fixtures'
```

**Describe alternatives you've considered**
Add notation to siginify _which_ capability an output belongs to if there are multiple usages. For example, showing that content comes from `testFixtures` vs. `default`.

Alternately, including all capabilities in the output of just `--id ':other-project'` would work!

**Additional context**

**Comment by autonomousapps** [comment]
I don't entirely follow this request. Could you share a sample of the expected output from such a feature?

**Comment by Nava2** [comment]
This may be user error, but if you have a build that leverages `java-test-fixtures` ([Docs](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures)), it will add a dependency on a project with a capability rather than the normal project. 

If you want to look at the "reason" output, i.e. figure out why that dependency is used in the project, there's no way to request it today. Calling `--id ':other-project'` will either return "unused" if it's not used, or if both `testFixtures(project(":other-project"))` and `project(":other-project")` are used, it'll give the result for `project(":other-project")` leaving no way currently to request to know why the `testFixtures` capability is requested.

**Comment by Nava2** [comment]
Here's a project: https://github.com/Nava2/dependency-analysis-test-fixtures-project-example

```bash
$ ./gradlew :lib:reason --id ":other-project"

> Configure project :
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.9.20` that might work differently than in the requested version `1.9.22`.

> Task :lib:reason

----------------------------------------
You asked about the dependency ':other-project'.
There is no advice regarding this dependency.
----------------------------------------

Shortest path from :lib to dependency-analysis-test-fixtures-project-example:other-project for compileClasspath:
:lib
\--- dependency-analysis-test-fixtures-project-example:other-project

Shortest path from :lib to dependency-analysis-test-fixtures-project-example:other-project for runtimeClasspath:
:lib
\--- dependency-analysis-test-fixtures-project-example:other-project

Shortest path from :lib to dependency-analysis-test-fixtures-project-example:other-project for testCompileClasspath:
:lib
\--- dependency-analysis-test-fixtures-project-example:other-project

Shortest path from :lib to dependency-analysis-test-fixtures-project-example:other-project for testRuntimeClasspath:
:lib
\--- dependency-analysis-test-fixtures-project-example:other-project

Source: main
------------
(no usages)

Source: test
------------
* Uses 1 class: com.example.dependency_analysis.TestFixture (implies testImplementation).
```

I'm unsure how to get advice for why the `testFixture(project(":other-project"))` is applied

**Comment by Nava2** [comment]
@autonomousapps I added some more context, I had my initial question incorrect as the test fixture content _is_ there. It's just not marked/obvious what is coming from where. I updated the initial description and my previous comment! Apologies for confusion.

**Comment by autonomousapps** [comment]
@jjohannes this might be something interesting for us to take a look at.

**Comment by Nava2** [comment]
The `capability` information appears to be in the JSON output, so I hope this is just a visualization change 😅

**Comment by arthurrogel** [comment]
Hey, just noting here, I ran into this same issue today, the parameter proposed by @Nava2 would definitely be helpful to me as well!

**Comment by seregamorph** [comment]
This seems to be related https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1170
