### ISSUE TITLE
[TestKit Plugin] gradle-testkit-support version problem

### ISSUE THREAD

**Issue by friscoMad** [autonomousapps/dependency-analysis-gradle-plugin#1109]
**Plugin version**
0.9

**Gradle version**
8.1.1

**JDK version**
OpenJDK 11

**Describe the bug**
There are some issues with the latest version released for the TestKit plugin.
First of all the default `withSupportLibrary` points to an unreleased 0.16 version of the support lib, that was fixed in this [commit](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/commit/47ab5f1e04e6bff856d1c2b71ba227580949f7e3) but not released.
Not a big deal as you can set your own value, but using the latest `gradle-testkit-truth` library also fails as it depends on an unreleased 0.16-SNAPSHOT version of the support library.
You can see it even in the maven repo: https://mvnrepository.com/artifact/com.autonomousapps/gradle-testkit-truth/1.6
Using 0.15 works (and using 0.16 and constraints should work too) but it is a bit difficult to understand why everything fails if you follow the readme (which also needs some updates) 

**To Reproduce**
1. Create new project
2. Add the plugin and support/truth dependencies to it
3. Run any gradle command 

**Expected behavior**
Works

**Additional context**

**Comment by autonomousapps** [comment]
Thanks for the issue! I am aware of that problem and it has been fixed on `main` already -- but I haven't published a new release with that fix. I will do that.

**Comment by autonomousapps** [comment]
This has been resolved.
