### ISSUE TITLE
Could not determine the dependencies of task ':app:synthesizeProjectViewDebugTest'.

### ISSUE THREAD

**Issue by giovanischiar** [autonomousapps/dependency-analysis-gradle-plugin#1111]
**Build scan link**
https://scans.gradle.com/s/4qwwjyf5chvkk

**Plugin version**
latest snapshot "+"

**Gradle version**
8.2

**JDK version**
17

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**
1.9.21 

**(Optional) Android Gradle Plugin (AGP) version**
8.2.1

**Describe the bug**
When I add the `id("com.autonomousapps.dependency-analysis") version "+"` to root build.gradle and run `./gradlew projectHealth` I got this error Could not determine the dependencies of task ':app:synthesizeProjectViewDebugTest'.

**To Reproduce**
1. Add `id("com.autonomousapps.dependency-analysis") version "+"` to root build.gradle
2. Go to terminal and run `./gradlew projectHealth `

**Expected behavior**
The default output for projectHealth

**Comment by autonomousapps** [comment]
Thanks for the issue!

Hopefully the build scan will be enough, but do you have a minimal reproducer? Those repro steps don't look sufficient to me.

**Comment by gabrielittner** [comment]
I've got a reproducer, this is a new project created with Android Studio Hedgehog with the only change being that I added this plugin [MyApplication.zip](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/files/14068667/MyApplication.zip)

**Comment by ZacSweers** [comment]
Here's another repro, just uncomment the commented out enabling of DAGP in the root build.gradle.kts: https://github.com/ZacSweers/CatchUp

**Comment by autonomousapps** [comment]
> I've got a reproducer, this is a new project created with Android Studio Hedgehog with the only change being that I added this plugin [MyApplication.zip](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/files/14068667/MyApplication.zip)

@gabrielittner I downloaded this zip and ran `buildHealth` on it and there were no errors. Is there something I'm missing?

**Comment by gabrielittner** [comment]
I can still reproduce it when I download the zip and run buildHealth. However after deleting `~/.android/analytics.settings` it doesn't reproduce anymore and as soon as the file is recreated. Just the existence of the file seems to be enough, so you should be able to reproduce it by just creating it without content.

**Comment by autonomousapps** [comment]
how is that file used? I'm not familiar with it. do you have an example with actual content? links to documentation?

**Comment by autonomousapps** [comment]
I just checked and I already have such a file in my environment. The contents of it are
```
{"userId":"73484633-8bc3-4f83-9fcb-edcf4ec64b4e","hasOptedIn":false,"debugDisablePublishing":false,"saltValue":0,"saltSkew":-1}
```

**Comment by gabrielittner** [comment]
Mine looks the same and it's created/updated when you toggle "send usage statistics to Google" in Android Studio, other than that I don't know more about it. I was just thinking about it since the issue is analytics related. For me it happens regadless of whether `"hasOptedIn"` is true or false but maybe changing it true will help reproducing it?

**Comment by autonomousapps** [comment]
I changed the value to true and reran buildHealth (with `--rerun-tasks`) and it worked fine :shrug:

Have you tried with rerun-tasks?

**Comment by gabrielittner** [comment]
`--rerun-tasks` didn't help. I tried aroudn a bit more and it looks like you need to kill the daemon after changing hasOptedIn or generally use `--no-daemon` for the change to take effect.

**Comment by autonomousapps** [comment]
`--no-daemon` did it 🤔

**Comment by autonomousapps** [comment]
I can eliminate the error by basically commenting out this method body for android unit tests. Given the whole chain is nullable, it is bizarre to me that this happens. It looks like an AGP bug.
```
  override fun getAndroidRes(): Provider<Iterable<File>> {
    // return project.provider { emptyList() }
    return sources.res?.all
      ?.map { layers -> layers.flatten() }
      ?.map { directories ->
        directories.map { directory -> directory.asFileTree.matching(Language.filterOf(Language.XML)) }
      }
      ?.map { trees -> trees.flatten() }
      ?: project.provider { emptyList() }
  }
```

**Comment by autonomousapps** [comment]
https://issuetracker.google.com/issues/325307775
