### ISSUE TITLE
Reason id dependency filter ambiguity

### ISSUE THREAD

**Issue by seregamorph** [autonomousapps/dependency-analysis-gradle-plugin#1124]
**Plugin version**
1.29.0

**Gradle version**
8.6

**JDK version**
17

**Describe the bug**
The `reason` task receives `--id` argument and filters dependency in a pretty lenient way. E.g. if the `module` has these dependencies:
* `project("list")`
* `project("list-A")`
* `project("list-B")`

and we call
```
./gradlew :module:reason --id list
```
if can pick any of those three modules (e.g. `list-A`). This depends on the combination of dependency scopes and order of definition.

**Expected behavior**
1. If the name of the dependency is specified fully, it should be preferred.
2. If there is am ambiguity and several dependencies match, it should throw exception instead of picking random first matching one

**Additional context**
The problem is around these two places in the code:
* https://github.com/autonomousapps/dependency-analysis-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt#L219
```
// picks first if several matches
val gavKey = dependencyUsages.entries.find(requestedId::matchesKey)?.key ?:
```
* https://github.com/autonomousapps/dependency-analysis-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/internal/utils/coordinatesStrings.kt#L32
```
// too lenient
  // finally the most lenient check
  if (startsWithKey(mapEntry)) return true
```

**To Reproduce**
Let me know if you need sample project to reproduce.

**Comment by seregamorph** [comment]
The solution proposed here: https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1125

**Comment by autonomousapps** [comment]
Thanks for the issue! This problem has annoyed me for a while, but I haven't had the bandwidth to focus on it. I appreciate the PR 👍

**Comment by seregamorph** [comment]
Addressed in https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1125
