### ISSUE TITLE
Unable to find method KotlinModuleMetadata.getKmModule() , explodeJarRelease is failing

### ISSUE THREAD

**Issue by gptshubham595** [autonomousapps/dependency-analysis-gradle-plugin#1177]
I'm working with multiple modules in android 

for DI I'm using Hilt (Dagger2)

:app (com.android.application), :presentation (com.android.library), :data(com.android.library) , :domain(com.android.library), :benchmark (com.android.test)

Now I added in top level gradle

plugins{
alias(libs.plugins.dependency.analysis)
}

allprojects {
    apply(plugin = "com.autonomousapps.dependency-analysis")
}

Now I'm running buildHealth everytime its failed for these three tasks and I don't know the reason

explodeJarRelease

**Comment by autonomousapps** [comment]
Please re-file this issue while using the issue template. A minimal reproducer will also be essential.
