### ISSUE TITLE
 Task ':explodeCodeSource' uses this output of task ':kspKotlin' without declaring an explicit or implicit dependency

### ISSUE THREAD

**Issue by Mrkchv** [autonomousapps/dependency-analysis-gradle-plugin#1185]
**Plugin version**
1.31.0

**Gradle version**
8.4

**JDK version**
17

**Kotlin and Kotlin Gradle Plugin (KGP) version**
1.9.20

**Android Gradle Plugin (AGP) version**
8.3.2

**Describe the bug**
After bumping to 1.31.0 we get this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':app:kspGoogleDebugKotlin' (type 'KspTaskJvm').
  - Gradle detected a problem with the following location: '/Users/Developer/StudioProjects/mobilebank-android/app/build/generated/ksp/googleDebug'.
    
    Reason: Task ':app:explodeCodeSourceGoogleDebug' uses this output of task ':app:kspGoogleDebugKotlin' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':app:kspGoogleDebugKotlin' as an input of ':app:explodeCodeSourceGoogleDebug'.
      2. Declare an explicit dependency on ':app:kspGoogleDebugKotlin' from ':app:explodeCodeSourceGoogleDebug' using Task#dependsOn.
      3. Declare an explicit dependency on ':app:kspGoogleDebugKotlin' from ':app:explodeCodeSourceGoogleDebug' using Task#mustRunAfter.
    
For more information, please refer to https://docs.gradle.org/8.4/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.
```

We can specify the dependency of the :explodeCodeSource task on :kspKotlin as follows and it will work:
```
allprojects.forEach { project ->
        project.tasks.withType<CodeSourceExploderTask>().configureEach {
            dependsOn(*project.tasks.withType<KspTaskJvm>().toTypedArray())
        }
}
```

Before bumping to 1.31.0 we used 1.25.0 and did not get the error. The error occurs on versions higher than 1.29.0.

**Comment by autonomousapps** [comment]
Thanks for the issue. Do you have a minimal reproducer?

**Comment by Mrkchv** [comment]
@autonomousapps Unfortunately I cannot share the code of our project. I also tried to make a test project, but I didn't get the error. Perhaps the logs will be useful 
[project_health_debug_log.txt.zip](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/files/15217763/project_health_debug_log.txt.zip)

**Comment by autonomousapps** [comment]
My working assumption is that this is another instance of [this Gradle bug](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/685), except that you say this only appears on 1.30.0 and higher. A reproducer would be very useful.

**Comment by StylianosGakis** [comment]
This https://issuetracker.google.com/u/0/issues/376709932 *might* be related here, as it was filed by the apollo-kotlin maintainers as a result of me getting the same error while trying to use this plugin long with apollo-kotlin.

**Comment by autonomousapps** [comment]
I've had a lot more experience with this recently, and I no longer consider it a Gradle bug (except when it's about an actual Gradle core plugin), but instead incorrect wiring of task outputs from plugin authors. Which is to say, the `kspKotlin` task isn't registering its outputs as part of the relevant source sets.

There's really nothing for this plugin to do. Unless I get a minimal reproducer, I can only assume it's a bug in other plugins.

**Comment by martinbonnin** [comment]
For the record and for anyone bumping into this issue with the Apollo plugin, you can workaround by using `connectToAllAndroidVariants()`:

```
apollo {
  service("service") {
    packageName.set("com.example")
    outputDirConnection {
      connectToAllAndroidVariants()
    }
  }
}
```

See [this PR](https://github.com/HedvigInsurance/android/pull/2262) for an example (Thanks @StylianosGakis for diving into this!)

I'm not 100% sure if the bug is in AGP not honouring `kotlin.sourceSet["main"].srcDir()` or in Apollo not calling `variant.sources.kotlin.addGeneratedSourcesDirectory()`. Will update depending the AGP team thoughts here.
