### ISSUE TITLE
Run plugin for some specific modules only

### ISSUE THREAD

**Issue by 9tilov** [autonomousapps/dependency-analysis-gradle-plugin#1188]
Hi team! 
I have a question regarding plugin configuration. I integrated it for my work project but buildHealth task takes too much time. Is it possible to configure it somehow and run buildHealth task for specific modules only? I have looked into dependencyAnalysis extension but found only settings for specific module. It means if I run buildHealth all my modules will be checked. But I want to check specific modules only.

**Comment by autonomousapps** [comment]
You can run `./gradlew my-module:projectHealth` instead. This is noted in the readme [here](https://github.com/autonomousapps/dependency-analysis-gradle-plugin#project-health).
