### ISSUE TITLE
Adviced to add transitive which is exposed as Kotlin default value in used lib function

### ISSUE THREAD

**Issue by patrickneulichedldmde** [autonomousapps/dependency-analysis-gradle-plugin#1196]
**Build scan link**

**Plugin version**

1.32.0, also tried debugging using the main branch

**Gradle version**

8.7

**JDK version**

Temurin-17

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**

kotlin-gradle-plugin:2.0.0 using 1.9.24 gives the same result

**(Optional) Android Gradle Plugin (AGP) version**

**(Optional) `reason` output for bugs relating to incorrect advice**

<details>

<summary>Output</summary>

```
----------------------------------------
You asked about the dependency 'com.github.ajalt.mordant:mordant:2.5.0'.
You have been advised to add this dependency to 'testImplementation'. It matched a bundle rule: com.github.ajalt.mordant:mordant:2.5.0 was substituted for com.github.ajalt.mordant:mordant-jvm:2.5.0.
----------------------------------------

Shortest path from :renovate-notifier to com.github.ajalt.mordant:mordant:2.5.0 for compileClasspath:
:renovate-notifier
\--- com.github.ajalt.clikt:clikt:4.4.0
      \--- com.github.ajalt.clikt:clikt-jvm:4.4.0
            \--- com.github.ajalt.mordant:mordant:2.5.0

Shortest path from :renovate-notifier to com.github.ajalt.mordant:mordant:2.5.0 for runtimeClasspath:
:renovate-notifier
\--- com.github.ajalt.clikt:clikt:4.4.0
      \--- com.github.ajalt.clikt:clikt-jvm:4.4.0
            \--- com.github.ajalt.mordant:mordant:2.5.0

Shortest path from :renovate-notifier to com.github.ajalt.mordant:mordant:2.5.0 for testCompileClasspath:
:renovate-notifier
\--- com.github.ajalt.clikt:clikt:4.4.0
      \--- com.github.ajalt.clikt:clikt-jvm:4.4.0
            \--- com.github.ajalt.mordant:mordant:2.5.0

Shortest path from :renovate-notifier to com.github.ajalt.mordant:mordant:2.5.0 for testRuntimeClasspath:
:renovate-notifier
\--- com.github.ajalt.clikt:clikt:4.4.0
      \--- com.github.ajalt.clikt:clikt-jvm:4.4.0
            \--- com.github.ajalt.mordant:mordant:2.5.0

Source: main
------------
(no usages)

Source: test
------------
(no usages)
```

</details>

**Describe the bug**

The plugin tells me to add the transitive directly as `testImplementation("com.github.ajalt.mordant:mordant:2.5.0")`.
I don't directly use anything from this dependency.
I use `com.github.ajalt.clikt:clikt(-jvm)` and in my test I use the test function which has the following signature.
The `AnsiLevel` is from `mordant(-jvm)`, I suspect this is detected as a usage because of how kotlin default arguments are converted to bytecode, is that possible?
All I want to do is to understand if my understanding of when to add this as testimplementation (when I have an import statement for it) is correct.
Also clikt seems to correctly expose this as api dependency [see here](https://github.com/ajalt/clikt/blob/master/clikt-mordant/build.gradle.kts#L33), so the combination of me not using it directly and them exposing it should be enough, right?

![image](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/assets/169662472/8f746759-95a5-42aa-9cd4-1054f92b6715)

**To Reproduce**
Simply use Clickt in a dummy project and use the test method on `CliktCommand`
See for example this [repo](https://github.com/patrickneulichedldmde/clikt-hello-world).

**Expected behavior**

**Additional context**

**Comment by autonomousapps** [comment]
Thanks for the question.

It's not that there's a default argument, but that the public function includes a parameter with the type `AnsiLevel`.

It might be reasonable for you to create a bundle so you don't have to declare that library. See the [wiki](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/wiki/Customizing-plugin-behavior#logical-dependency-groups-aka-dependency-bundles).
