### ISSUE TITLE
How to change buildHealth task's dependencies

### ISSUE THREAD

**Issue by nuhkoca** [autonomousapps/dependency-analysis-gradle-plugin#1212]
**Plugin version**
1.32.0

**Gradle version**
8.8

**JDK version**
17

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**
1.9.22

**(Optional) Android Gradle Plugin (AGP) version**
8.3.2

**Describe the bug**
The task ends with the exception below

> Task :app:kaptNonMinifiedInternalKotlin FAILED

**To Reproduce**
This is an internal issue

**Expected behavior**
The task should terminate successfully.

**Additional context**
I use Android [Macrobenchmark Gradle plugin](https://developer.android.com/topic/performance/benchmarking/macrobenchmark-overview). This plugin adds more build types besides `release`, `debug` such as `nonMinifiedRelease`, etc. And somehow buildHealth depends on the all build types and failing. Is there a way to override what buildHealth is supposed to depend? `nonMinifiedRelease` is not a used build type and we are not adding most dependencies to it.

**Comment by autonomousapps** [comment]
Why is that task failing?

If you want to ignore certain variants, see [this issue](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1213).
