### ISSUE TITLE
How can I ignore specific flavor & build type?

### ISSUE THREAD

**Issue by trietbui85** [autonomousapps/dependency-analysis-gradle-plugin#1213]
**Is your feature request related to a problem? Please describe.**

My project has 2 flavors (dev & google) and 3 build types (debug, release, releasedebuggable).
But I only want to run dependency analysis task for `devDebug` or `googleDebug`.

**Describe the solution you'd like**

I want to add the variant configuration of that flavor & build type to `gradle.properties`.

**Describe alternatives you've considered**

**Additional context**

I notice we can ignore a specific build type (`dependency.analysis.android.ignored.variants=release`) but it's not enough for me.

**Comment by autonomousapps** [comment]
```properties
dependency.analysis.android.ignored.variants=<list,of,variants>
```
where `variant` means the combination of flavor + buildType. You need to be very explicit and specify the full variant name.
