### ISSUE TITLE
Kotlin plugin must be loaded in same (or parent) classloader to DAGP: add check and print actionable error message

### ISSUE THREAD

**Issue by pkubowicz** [autonomousapps/dependency-analysis-gradle-plugin#1222]
**Build scan link**
https://scans.gradle.com/s/zjpogemu7wc4a

**Plugin version**
1.32.0

**Gradle version**
8.8

**JDK version**
17.0.11

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**
Kotlin 1.9.22 bundled inside Gradle 8.8

**Describe the bug**
Applying `com.autonomousapps.dependency-analysis` crashes Gradle during configuration phase.

```
Caused by: java.lang.TypeNotPresentException: Type org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension not present	
	at org.gradle.api.reflect.TypeOf.captureTypeArgument(TypeOf.java:299)	
	at org.gradle.api.reflect.TypeOf.<init>(TypeOf.java:96)	
	at com.autonomousapps.subplugin.ProjectPlugin$KotlinSources$special$$inlined$the$3.<init>(TypeOfExtensions.kt:28)	
	at com.autonomousapps.subplugin.ProjectPlugin$KotlinSources.<init>(ProjectPlugin.kt:1064)	
	at com.autonomousapps.subplugin.ProjectPlugin.configureKotlinJvmProject(ProjectPlugin.kt:472)	
	at com.autonomousapps.subplugin.ProjectPlugin.access$configureKotlinJvmProject(ProjectPlugin.kt:59)
```

**To Reproduce**
Project is very minimal, has root build.gradle.kts and one subproject.

Root:

```
plugins {
    id("com.autonomousapps.dependency-analysis") version "1.32.0"
}
```

my-plugin/build.gradle.kts

```
plugins {
    `kotlin-dsl`
}

gradlePlugin {
    plugins {
        create("myPlugin") {
            id = "pl.pkubowicz.myplugin"
            implementationClass = "pl.pkubowicz.MyPlugin"
            displayName = "My Plugin"
            version = project.version as String
        }
    }
}

repositories {
    mavenCentral()
}
```

The bug does not appear when the same configuration is used for a single-project build.

**Expected behavior**
I can execute `gradle build` as well as `gradle buildHealth`.

**Additional context**

**Comment by autonomousapps** [comment]
This is basically the same problem as described at the link below, with the same basic solution: the `kotlin-dsl` plugin needs to be loaded in the same or a parent classloader to DAGP.

https://github.com/autonomousapps/dependency-analysis-gradle-plugin/wiki/FAQ#typenotpresentexception-type-orgjetbrainskotlingradledslkotlinprojectextension-in-kotlin-jvm-library.

**Comment by pkubowicz** [comment]
Can the plugin be better at communicating the failure?

Good error messages give actionable advice. 'TypeNotPresentException' does not show user what action to take; it rather looks like a plugin author's mistake. It's a bit like showing NPE to a user – user won't expect that they should change the configuration.

For example, when Gradle crashes due to problems with Configuration Cache, they show you a link to Gradle User Guide covering how to fix common problems with Configuration Cache.

If the problem here is so common that it appeared in FAQ, maybe it should be handled in code? Even by catching the exception and displaying the link to FAQ you showed me.

**Comment by autonomousapps** [comment]
That's a fair point.

**Comment by pkubowicz** [comment]
Thank you!
