### ISSUE TITLE
Allow bundles to be configured in DependencyAnalysisSubExtension

### ISSUE THREAD

**Issue by matejdro** [autonomousapps/dependency-analysis-gradle-plugin#1234]
**Is your feature request related to a problem? Please describe.**

In our project we are using [gradle convention plugins](https://docs.gradle.org/current/samples/sample_convention_plugins.html) to apply dependency analysis config on every module, with `dependency.analysis.autoapply=false`. Problem is that we can't declare `bundles` config with this, we have to declare bundles on our top-level project only, so we have to split config for the DAGP into two different places

**Describe the solution you'd like**

I would like to be able to declare `structure` and `bundles` in per-project config, so the entire DAGP config can be in the same place

**Describe alternatives you've considered**

Currently the only alternative is to split the config into two different configs (one for per-project config and one top level for bundles config).

**Comment by autonomousapps** [comment]
Thanks for the issue. I will not be implementing such a feature. I understand that might be a frustrating response, but I simply do not have the time.
