### ISSUE TITLE
Plugin does not find catalog entires if only applied to subprojects

### ISSUE THREAD

**Issue by jjohannes** [autonomousapps/dependency-analysis-gradle-plugin#1256]
**Is your feature request related to a problem? Please describe.**

Starting with `2.0.0`, the plugin can be applied to subprojects only without the need to apply it to the root  🎉 . In that cases however, catalog entries are not discovered and the original coordinates are used in advices instead.

I see this:

```
  Unused dependencies which should be removed:
    implementation("com.google.inject:guice:5.1.0")
  
  Existing dependencies which should be modified to be as indicated:
    implementation("org.jboss.resteasy:resteasy-core:4.7.6.Final") (was api)
  
  Dependencies which should be removed or changed to runtime-only:
    runtimeOnly("org.jboss.resteasy:resteasy-jackson2-provider:4.7.6.Final") (was implementation)
```

When I would like to see this:

```
Unused dependencies which should be removed:
  implementation(libs.guice)

Existing dependencies which should be modified to be as indicated:
  implementation(libs.resteasy.core) (was api)

Dependencies which should be removed or changed to runtime-only:
  runtimeOnly(libs.resteasy.jackson2.provider) (was implementation)
```

**Describe the solution you'd like**

I would like to apply the plugin only in subprojects (in a convention plugin based setup) but still have the "catalog integration" available.

**Describe alternatives you've considered**

I can apply the plugin in the root in addition to get the desired behavior.

**Additional context**

The issue can be observed in this project: https://github.com/jjohannes/gradle-project-setup-howto

Remove the line `id("com.autonomousapps.dependency-analysis")` from the root build Gradle:  https://github.com/jjohannes/gradle-project-setup-howto/blob/main/build.gradle.kts#L5
And change a dependency scope in one of the `build.gradle.kts` files to see the effect.

**Comment by autonomousapps** [comment]
Thanks for the report!

**Comment by jjohannes** [comment]
Thank's for the fix @autonomousapps!
