### ISSUE TITLE
Advice if a module should be converted to jvm module

### ISSUE THREAD

**Issue by ritesh-singh** [autonomousapps/dependency-analysis-gradle-plugin#1259]
**Is your feature request related to a problem? Please describe.**

Dependency analyser is doing a great job in advising the correct configuration scope for the dependencies and helping in removing unused dependencies, for the classpath. It would be great to have a feature which can also advice if a certain module can be changed to jvm module.

**Describe the solution you'd like**
Advice on module level - if a certain module can be changed to jvm module.

**Describe alternatives you've considered**
Create a separate plugin to do the same job, inspired from this plugin.

**Additional context**

**Comment by autonomousapps** [comment]
The plugin already does this! If an Android module uses no or limited Android features, the plugin will let you know.

**Comment by ritesh-singh** [comment]
Thanks, i wasn't aware of the feature. It would be great if it can advice if a module can be converted to jvm module by removing direct dependencies it depends on or removing the applied script plugins, which might be bringing android related assets/deps/plugins.

Currently it advices on moving to jvm module like you mentioned if a module has no or limited android features, but it doesn't hold true for cases where a module must be depending on an android module but not using any android feature.

**Comment by ritesh-singh** [comment]
Thanks, i wasn't aware of the feature.

Is it possible, if it can advice either a module needs to be converted to jvm module or not, for cases when it doesn't see a direct/transitive android dependency but the plugin applied to the module is wrong (android plugin instead of jvm plugin).

Looking at the [logic](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/blob/c99d6e04558b44a3c079b81ff206496e4a1160ab/src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt#L143)
looks like it either advices if a module can be a jvm module or limited Android feature as you called out.

Having a flag or option for opting-in only for advising if a module can be changed to jvm moudule, if it has no direct/transitive dependency on android stuff or any android assets will be great to have.

**Comment by ritesh-singh** [comment]
👋  I might have not communicated properly in above comment. I was more thinking on the lines - to tell `ReasonTask` to not consider the transitive dependencies coming from script plugins (plugin with android plugin applied + bunch of other android dependencies it brings).

That, will help projects in evaluating if a module can be changed to jvm module by just changing android script plugin to jvm script plugin.

**Comment by autonomousapps** [comment]
You can run `./gradlew <module>:reason --module android`, you'll get more information advice relating to jvm vs android.

You can also look at the files at `build/reports/dependency-analysis/<variant>/android-score.json`, you'll see more detail about the Android features used by a module. That file is generated when running `buildHealth` or `projectHealth`. Let me know if that's useful for you.
