### ISSUE TITLE
buildhealth stuck on complieAppKotlin

### ISSUE THREAD

**Issue by Sara-Tareq** [autonomousapps/dependency-analysis-gradle-plugin#1266]
**Build scan link**

**Plugin version**
2.0.2

**Gradle version**
8.10

**JDK version**
17

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**
2.0.20

**(Optional) Android Gradle Plugin (AGP) version**
8.5.2

**Describe the bug**
The buildhealth task doesn't give any output and it get frozen on the compileAppKotlin stage

**To Reproduce**
 ./gradlew buildhealth

**Comment by autonomousapps** [comment]
There is not nearly enough detail to give a proper response. I'm closing this issue. Feel free to reopen with an actual reproducer.
