### ISSUE TITLE
Health task throws error 

### ISSUE THREAD

**Issue by Mitua1221** [autonomousapps/dependency-analysis-gradle-plugin#1282]
**Plugin version**
2.1.4

**Gradle version**
8.10.2 and 8.8 also

**JDK version**
17 

**(Optional) Android Gradle Plugin (AGP) version**
28.2.0 and 8.7.0 too has ths problem

**Describe the bug**
Task :projectHealth  just not works, throws error. 

**To Reproduce**
1. Add plugins as described in a documentation 
2. Add plugins to modules that i want to scan 
3. Run task :projectHealth  

-> failure

```
Unable to find method ''com.google.common.collect.ImmutableSet com.google.common.graph.Graphs.reachableNodes(com.google.common.graph.Graph, java.lang.Object)''
'com.google.common.collect.ImmutableSet com.google.common.graph.Graphs.reachableNodes(com.google.common.graph.Graph, java.lang.Object)'Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
```

**Expected behavior**
Task executes correctly, without trowing errors. 

**Additional context**
-

**Comment by autonomousapps** [comment]
You must have an older version of Guava on your buildscript classpath, in a classloader with higher precedent. buildSrc perhaps.
