### ISSUE TITLE
Update "bundles" Wiki

### ISSUE THREAD

**Issue by engi2nee** [autonomousapps/dependency-analysis-gradle-plugin#1294]
Hi,
Thanks for the awesome library, we have been using it for quite sometime, and is quite useful!.

We spent sometime trying to understand what's wrong after the major update, as our builds were failing with the following error:
> "A problem occurred evaluating script.
Could not find method bundle() for arguments [kotlin-stdlib, dependency_analysis_dvsliagx61bjs063tibt8j0yl$_run_closure1$_closure4$_closure6@30851adc] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler"

Until we noticed that "bundle" should be nested under "structure" not "dependencies" like the wiki says:

https://github.com/autonomousapps/dependency-analysis-gradle-plugin/wiki/Customizing-plugin-behavior#logical-dependency-groups-aka-dependency-bundles

**Comment by autonomousapps** [comment]
Thanks for letting me know! I've updated the wiki.

Please note that the old name, `dependencies`, has been deprecated for a while :) Were the deprecation warnings not showing up in your IDE or build logs?
