### ISSUE TITLE
False positive where interface in another module is used

### ISSUE THREAD

**Issue by mr-thierry** [autonomousapps/dependency-analysis-gradle-plugin#1302]
**Build scan link**

**Plugin version**
2.4.2

**Gradle version**
8.10.2

**JDK version**
21

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**
2.0.21

**(Optional) Android Gradle Plugin (AGP) version**
AGP 8.7.1

**(Optional) `reason` output for bugs relating to incorrect advice**

**Describe the bug**
False positive when executing `projectHealth`. 

In `module-a`, have a class that uses another class:

```
class MyClass {
   var foo = Foo()
}
```

Foo is in `module-b` and is defined like so:
```
class Foo: Bar
```

`Bar` is an interface in `module-c`. Both `module-a` and `module-b` include `module-c` with `implementation` (not `api`).

**To Reproduce**
1. Execute `projectHealth`

The error is:

```
Unused dependencies which should be removed:
    implementation project(':module-c')
```

But removing `module-c` breaks the compilation.

**Expected behavior**
The build is successful

**Additional context**

**Comment by autonomousapps** [comment]
Closing pending contrary information.

**Comment by mr-thierry** [comment]
Right. Make sense. Thanks for the follow-up!
