### ISSUE TITLE
fixDependencies task added dependency incorrectly

### ISSUE THREAD

**Issue by zepurplez** [autonomousapps/dependency-analysis-gradle-plugin#1313]
**Plugin version**
2.4.2

**Gradle version**
8.11

**JDK version**
17

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**
1.9.24

**Describe the bug**
There is a kotlin project with java-test-fixture plugin. `src/main` has only one class with arguments from library(jodatime for example) and stub implementation in `src/testFixtures`.

**build.gradle.kts**
```kotlin
plugins {
    kotlin("jvm") version "1.9.24"
    `java-test-fixtures`
    id("com.autonomousapps.dependency-analysis") version "2.4.2"
}

dependencies {
    api("joda-time:joda-time:2.12.5") {
        artifact {
            classifier = "no-tzdb"
        }
    }
}
```

**src/main**
```kotlin 
interface SomeHandler {
    fun handle(date: DateTime)
}
```

**src/testFixtures**
```kotlin 
class StubSomeHandler : SomeHandler {
    override fun handle(date: DateTime) = TODO()
}
```

So when you try to run a command `./gradlew :lib:fixDependencies` it will add new dependency to `testFixturesApi` configuration and it will be looks like this:
```
dependencies {
    api("joda-time:joda-time:2.12.5") {
        artifact {
            classifier = "no-tzdb"
        }
      testFixturesApi("joda-time:joda-time:2.12.5")
}
}
```

**Expected behavior**
```
dependencies {
    api("joda-time:joda-time:2.12.5") {
        artifact {
            classifier = "no-tzdb"
        }
    }
    testFixturesApi("joda-time:joda-time:2.12.5")
}
```

**Comment by zepurplez** [comment]
There is another way to specify dependency with classifier or artifactType

```kotlin
dependencies {
    api(variantOf(libs.jodaTime) { classifier("no-tzdb") })
}
```

In this case, running `./gradlew :lib:fixDependencies` won't give any advice to adding the dependency to the testFixtures configuration.

**Comment by autonomousapps** [comment]
Thanks for the report! Can you please try again with v2.5.0? it was just released yesterday, and it has improved support for parsing and rewriting .gradle.kts files.

**Comment by autonomousapps** [comment]
Great, thanks for confirming! I'll close this issue then.
