### ISSUE TITLE
Duplicate dependency declaration resulting in wrong configuration name in advice

### ISSUE THREAD

**Issue by mvegter** [autonomousapps/dependency-analysis-gradle-plugin#788]
**Build scan link**
None

**Plugin version**
latest: 1696792142a47fbc610d6faf3e502da3c63d2c9f

**Gradle version**
7.5.1

**`reason` output for bugs relating to incorrect advice**
```
...:reason --id commons-beanutils:commons-beanutils:1.9.3

> Task ...:reason

----------------------------------------
You asked about the dependency 'commons-beanutils:commons-beanutils:1.9.3'.
You have been advised to remove this dependency from 'implementation'.
----------------------------------------

...

Source: main
------------
* Uses 1 class: org.apache.commons.beanutils.BeanUtils (implies implementation).
```

**Describe the bug**
```
> Unused dependencies which should be removed:
    implementation 'commons-beanutils:commons-beanutils:1.9.3'
```

**To Reproduce**
Found this through some convention plugin that added dependencies which were already applied and used on the project, effectively the build.gradle of the (sub)project looked like this:
```
    implementation 'commons-beanutils:commons-beanutils:1.9.3'
    runtimeOnly 'commons-beanutils:commons-beanutils:1.9.3'
```

**Expected behavior**
The suggestion should be on removing the `runtimeOnly` entry and not the `implementation` one

**Additional context**
`synthetic-project.json`
```json
      "imports": [

        "org.apache.commons.beanutils.BeanUtils",

      ]
    },
```
`traces.json`
```json
    {
      "coordinates": {
        "type": "module",
        "identifier": "commons-beanutils:commons-beanutils",
        "resolvedVersion": "1.9.3"
      },
      "bucket": "IMPL",
      "reasons": [
        {
          "type": "impl",
          "reason": "Uses class org.apache.commons.beanutils.BeanUtils"
        }
      ]
    },
```

**Comment by jjohannes** [comment]
This is probably fixed by #807

**Comment by jjohannes** [comment]
I this still an issue in the latest release (1.25.0) or can it be closed?

**Comment by autonomousapps** [comment]
Since it has been a month and no response to the request for more information, closing. Feel free to re-open if you have more information.
