### ISSUE TITLE
Gradle deprecation warning: `STABLE_CONFIGURATION_CACHE`

### ISSUE THREAD

**Issue by boris-petrov** [autonomousapps/dependency-analysis-gradle-plugin#792]
**Plugin version**
1.13.1

**Gradle version**
7.5.1

**Describe the bug**
Running the plugin on Gradle 7.5.1 with `enableFeaturePreview 'STABLE_CONFIGURATION_CACHE'` in `settings.gradle` leads to:

```
> Task :subproj:explodeJarMain
Build service 'inMemoryCache' is being used by task ':subproj:explodeJarMain' without the corresponding declaration via 'Task#usesService'. This will fail with an error in Gradle 8.0. Declare the association between the task and the build service using 'Task#usesService'. Consult the upgrading guide for further information: https://docs.gradle.org/7.5.1/userguide/upgrading_version_7.html#undeclared_build_service_usage
```

I see a similar one for `findInlineMembers` and `findDeclaredProcs`.

**Expected behavior**
No deprecation warning.

**Comment by autonomousapps** [comment]
Does this still happen with Gradle 8?

**Comment by boris-petrov** [comment]
It doesn't! Thanks for the ping. Not sure if Gradle 8 helped or something else but there is no longer a deprecation warning. Thanks for the hard work on this awesome plugin!
