### ISSUE TITLE
Add a gradle property to disable the AGP version warning

### ISSUE THREAD

**Issue by eygraber** [autonomousapps/dependency-analysis-gradle-plugin#848]
Other plugins like [android-cache-fix](https://github.com/gradle/android-cache-fix-gradle-plugin/blob/main/src/main/groovy/org/gradle/android/Versions.groovy#L57) and KMP provide this.

Keep in mind - https://youtrack.jetbrains.com/issue/KT-52244/Kotlin-MPP-stability-warning-even-though-gradle-property-is-set

**Comment by autonomousapps** [comment]
Thanks for the issue. Do you want to implement this?

**Comment by eygraber** [comment]
I could do it when I have the time.

**Comment by eygraber** [comment]
Looks like this was handled by https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/920
