### ISSUE TITLE
import kotlinx.coroutines.rx3.await mistakenly marked as unused

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-gradle-plugin#863]
**Build scan link**

**Plugin version**

1.19.0

**Gradle version**

7.6

**(Optional) Android Gradle Plugin (AGP) version**

7.4.1

**`reason` output for bugs relating to incorrect advice**

**Describe the bug**

The following snippet in our codebase is incorrectly resulting in the `org.jetbrains.kotlinx:kotlinx-coroutines-rx3` dependency getting marked as unused

```kotlin
import kotlinx.coroutines.rx3.await

// ...
class Presenter {
  fun example() {
    jobs +=
      viewModelScope.launch {
        runCatching {
            val usersMap = async { userRepository.get().getUsers(userIds).await() } // <-- used here
        }
      }
  }
}
```

I do see it identified in `exploded-source.json` under the `Presenter` class's imports. I also see it in the decompiled resulting class file

<img width="958" alt="image" src="https://user-images.githubusercontent.com/1361086/217734512-f59813a5-afed-4818-93b2-96a45c1f22dd.png">

**To Reproduce**
1. Use the above import in code structured like the example

**Expected behavior**

It should not advice removing this dependency

**Additional context**

**Comment by ZacSweers** [comment]
I do _not_ see it referenced in `inline-usage.json`, though I do see others 🤔

```json
  {
    "coordinates": {
      "type": "module",
      "identifier": "org.jetbrains.kotlinx:kotlinx-coroutines-rx3",
      "resolvedVersion": "1.6.4"
    },
    "inlineMembers": [
      {
        "packageName": "kotlinx.coroutines.rx3",
        "inlineMembers": [
          "collect"
        ]
      },
      {
        "packageName": "kotlinx.coroutines.rx3",
        "inlineMembers": [
          "seenValue",
          "subscription",
          "value"
        ]
      }
    ]
  },
```

**Comment by autonomousapps** [comment]
Is this still an issue with 1.27.0?

**Comment by autonomousapps** [comment]
I'm going to close this for now. If it's still an issue, please re-open.
