### ISSUE TITLE
A flag to automatically update dependencies based on suggestions by `projectHealth`

### ISSUE THREAD

**Issue by deepwritescode** [autonomousapps/dependency-analysis-gradle-plugin#869]
**Is your feature request related to a problem? Please describe.**
I'm working on breaking down a rather massive module in our codebase by folder, but we have a ton of dependencies so combing through all them isn't very scalable. 

**Describe the solution you'd like**
I really wish there was some way for me to just pass a flag to the `projectHealth` command like `--autoFormat` where the tool would take the advice and literally apply it. Something that would work like the auto-formatter for the imports in an Android studio project.

**Describe alternatives you've considered**
Given I don't know very much about this tool, I've just been diffing the gradle dependencies line by line manually. But I had some down time during lunch, so I made a little scratch file with a function that takes the suggested imports to be removed by the `project-health-report.txt` under the `Unused dependencies which should be removed:` section and returns a string of updated dependencies for me.

**Additional context**
The function I mentioned above which does what I need. Maybe I can open a PR if pointed to the right direction.
```
/**
 * Cleans up the dependencies given the suggestion from the project-health-report.txt
 *
 * @param depsStr the contents of the dependency block in the gradle file (Assuming the dependencies are in alphabetical order)
 * @param depsToRemove list of dependencies to remove listed in the project-health-report.txt (Assuming the dependencies are in alphabetical order)
 * @return the list of dependencies without the dependencies listed in [depsToRemove] 
 * */
fun cleanupDeps(
  depsStr: String,
  depsToRemove: String,
): String {
  val result = mutableListOf<String>()
  val deps = depsStr.lines()
  val toRemove = depsToRemove.lines().toMutableList()
  for (dep in deps) {
    val removeDep = toRemove.firstOrNull { it.isNotBlank() || it.isNotEmpty() }
    if (removeDep == dep) toRemove.removeAt(0) else result.add(dep)
  }
  return deps.joinToString(separator = "\n")
}
```

**Comment by autonomousapps** [comment]
I think what you're looking for is `fixDependencies`. Described [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/CHANGELOG.md#version-1110-1111-1112-1113) and [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/CHANGELOG.md#version-1130-1131).
