### ISSUE TITLE
testInstrumentationRunner dependencies are not recognized

### ISSUE THREAD

**Issue by Vichy97** [autonomousapps/dependency-analysis-gradle-plugin#873]
**Plugin version**
1.19.0

**Gradle version**
7.5

**`reason` output for bugs relating to incorrect advice**
`UnusedDepdencies`

**Describe the bug**
This plugin does not recognize dependencies where the classes used are referenced solely in the build.gradle. For example test runner classes used for `testInstrumentationRunner` will not be recognized and will be removed as unused, but this will cause tests to fail.

**Comment by autonomousapps** [comment]
Thanks for the issue. Can you provide a minimal reproducer?

**Comment by Vichy97** [comment]
https://github.com/Vichy97/Dependency-Analysis-Minimal-Repro/tree/issue_873 If you checkout `issue_873` branch and run `./gradlew fixDependencies` you will see it remove the dependency on `module_b` which causes tests to fail

**Comment by autonomousapps** [comment]
Cloning the repo and running `buildHealth`, the report says
```
> Task :buildHealth
Advice for :module_a
Unused dependencies which should be removed:
  androidTestImplementation(project(":module_b"))
```
I'm making this comment just to note that the issue appears before `fixDependencies` -- the advice is to remove the dependency, which `fixDependencies` simply follows. With this reproducer, I ought to be able to fix the issue. Thanks!

**Comment by autonomousapps** [comment]
@Vichy97 should your `:module_b` actually be `androidTestRuntimeOnly`? Since it's not used at compile time, I think that makes sense. Could you double-check in your project?
