### ISSUE TITLE
Configuration Cache: graphViewDebug should be compatible

### ISSUE THREAD

**Issue by Vichy97** [autonomousapps/dependency-analysis-gradle-plugin#874]
**Build scan link**
https://gradle-enterprise.aws.squarecloudservices.com/s/urmeyokxgt2n6

**Plugin version**
1.19.0

**Gradle version**
7.5

**Describe the bug**
Running `:reason` for a particular dependency is failing on the task `graphViewDebug`

**Comment by Vichy97** [comment]
I'm realizing this happens because this plugin is incompatible with configuration cache. running with `--no-configuration-cache` seems to always fix this issue.

**Comment by autonomousapps** [comment]
Ah ok. Probably should add the `notCompatibleWithConfigurationCache()` call to this task.... If you wanted to PR that, I'd accept it.

**Comment by autonomousapps** [comment]
This is done.
