### ISSUE TITLE
Interface extended by inner protected class is not recognized

### ISSUE THREAD

**Issue by Vichy97** [autonomousapps/dependency-analysis-gradle-plugin#881]
**Plugin version**
1.19.0

**Gradle version**
7.5

**Describe the bug**
The plugin does not seem to recognize interfaces extended by inner classes. I have not tested whether or not this is limited to `protected` classes or not. Here is an example of when this occurs:
```
public final class Foo {
    protected class Barmpl extends Bar {
    
    }
}
```
In this case the module that provides the `Bar` interface should be pulled in via `api`, however the plugin does not recognize this and instead thinks that dependency is unused and removes it.

**Comment by autonomousapps** [comment]
Thanks for the issue.

**Comment by Vichy97** [comment]
@autonomousapps after attempting to make a minimal repro of this, I can no longer repro on 1.26.0. This can probably be closed
