### ISSUE TITLE
Candidate resolution DSL issue configuring dependencies

### ISSUE THREAD

**Issue by ianbrandt** [autonomousapps/dependency-analysis-gradle-plugin#891]
**Build scan link**
`gradlew --scan buildHealth`: https://scans.gradle.com/s/nl5ukhfciwirw

**Plugin version**
1.20.0

**Gradle version**
8.1.1

**IDE version**
IntelliJ Ultimate 2023.1

**Verified platforms**
Mac and Windows

**Describe the bug**
I'm getting an IDE warning and subsequent errors trying to [configure dependency bundles](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior#logical-dependency-groups-aka-dependency-bundles):

```kotlin
dependencyAnalysis {
	dependencies { // Candidate resolution warning (full text below)
		bundle("kotlinx-coroutines-core") { // Unresolved reference: bundle
			includeDependency("org.jetbrains.kotlinx:kotlinx-coroutines-core") // Unresolved reference: includeDependency
			includeDependency("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm") // Same unresolved reference
		}
	}
}
```

> Candidate resolution will be changed soon, please use fully qualified name to invoke the following closer candidate explicitly:
public final fun dependencies(action: Action<DependenciesHandler>): Unit defined in com.autonomousapps.DependencyAnalysisExtension

<img width="702" alt="dagp-dependencies-dsl" src="https://user-images.githubusercontent.com/709570/233739001-cb8f35a0-8e2e-496a-835c-b6382fb7f721.png">

**To Reproduce**
Reproducer: https://github.com/sdkotlin/sd-kotlin-spring-talks/tree/dagp-dependencies-configuration
Attempted change: https://github.com/sdkotlin/sd-kotlin-spring-talks/commit/5546c9f3f0178cdf2881ebd4b8a3b398b5c8df96

**Expected behavior**
There are no IDE warnings, and "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm" isn't reported as an unused dependency given the bundle configuration.

**Actual behavior**
Running `buildHealth` does succeed, but the bundle configuration appears to have no effect:

> Unused dependencies which should be removed:
>  integrationTestImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4")

**Additional context**
Perhaps this is just another Gradle 8 incompatibility, #851.

**Comment by ianbrandt** [comment]
I'm able to work around the issue by using `this.dependencies`:

```kotlin
dependencyAnalysis {
	this.dependencies {
		bundle("kotlinx-coroutines-core") {
			includeDependency("org.jetbrains.kotlinx:kotlinx-coroutines-core")
			includeDependency("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm")
		}
	}
}
```

**Comment by ZacSweers** [comment]
I think the solution here would just be to replace it with a new one and deprecate the previous. Maybe `dependencyHandling`?
