### ISSUE TITLE
lateinit property compileClasspath has not been initialized

### ISSUE THREAD

**Issue by Jacks0N23** [autonomousapps/dependency-analysis-gradle-plugin#894]
**Build scan link**
https://scans.gradle.com/s/y2ku66z6uexv6

**Plugin version**
tried at 1.20.0 and 1.19.0

**Gradle version**
8.0.2

**Kotlin version**
1.8.10, 1.8.20, 1.8.21

**(Optional) Android Gradle Plugin (AGP) version**
7.4.2

**Describe the bug**
```
* What went wrong:
Execution failed for task ':domain-closing-document:graphViewRelease'.
> lateinit property compileClasspath has not been initialized
```

**To Reproduce**
I'm running task projectHealth, but I cannot provide sample

**Expected behavior**
Shows list of incorrect dependencies

SOLUTION:
Problem occurs while using configuration cache, so to fix it you should run task with "--no-configuration-cache" parameter

**Comment by autonomousapps** [comment]
This will be resolved by https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1039

**Comment by autonomousapps** [comment]
Resolved now.
