### ISSUE TITLE
ABI seems broken in Kotlin 1.8.10 with respect to internal classes

### ISSUE THREAD

**Issue by JGulbronson** [autonomousapps/dependency-analysis-gradle-plugin#895]
Upgrading our project to Kotlin 1.8, and it seems that `internal` isn't being picked up on correctly anymore. I ran `:reason` to identify why it was suggesting a dependency be `api` instead of `implementation`, as well as `abiAnalysisMain`, and they showed the same thing. `internal` classes are showing as `public` instead.

**Comment by JGulbronson** [comment]
@autonomousapps just wondering if you have any updates

**Comment by elshad-faire** [comment]
Actually, upgrading the plugin to 1.20.0 fixes all the issues except the following:

> Unused dependencies which should be removed:
    testImplementation("() -> java.io.File?")

And this issue is fixed by changing the configuration to ignore it like below:

dependencyAnalysis {
  issues {
    onUnusedDependencies {
      exclude(
          "() -> java.io.File?"
      )
    }
  }
}

We can live with this configuration but is this normal?

**Comment by ianbrandt** [comment]
Just FYI, the "() -> java.io.File?" issue also manifests in #884.

**Comment by autonomousapps** [comment]
@JGulbronson can you confirm that https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/895#issuecomment-1561738838 is accurate?

**Comment by joshfriend** [comment]
I am noticing that this may be fixed in Kotlin 1.9-RC. All the missing dependencies that DAGP flagged when upgrading to Kotlin 1.8 are now listed as unused.
