### ISSUE TITLE
Bumping project to Gradle 8.0 breaks Android project analysis for java-library modules

### ISSUE THREAD

**Issue by jrodbx** [autonomousapps/dependency-analysis-gradle-plugin#898]
Note: this may only be for testImplementation dependencies!

Module-A: android library module
Module-B: java library module

Module-A build.gradle
```
    testImplementation projects.module.b
```

Constraint: Module A is actually referencing a class in Module B

Expected: no failure
Actual: is failing

```
* What went wrong:
Execution failed for task ':module:a:projectHealth'.
> Unused dependencies which should be removed:
    testImplementation project(':module:b')
```

**Comment by gmarques33** [comment]
@BraisGabin I think this is unrelated to the original issue. It's a issue with Kotlin 1.8.20: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/884 and can be resolved adding the following block to your gradle file:
```
dependencyAnalysis {
  issues {
    all {
      onAny {
        severity("fail")
        exclude("() -> java.io.File?")
      }
    }
  }
}
```

**Comment by autonomousapps** [comment]
Thanks for the report.

**Comment by autonomousapps** [comment]
Can you try the latest version (1.24.0 at time of writing)? There have been a lot of changes, including migrating to Gradle 8+ and AGP 7.4 (for compilation).
