### ISSUE TITLE
Invalid projectHealth - lombok/tests

### ISSUE THREAD

**Issue by Cililing** [autonomousapps/dependency-analysis-gradle-plugin#899]
Hi,

I wanted to use a plugin in a project. The output I got is:
```
Unused annotation processors that should be removed:
  testImplementation 'org.projectlombok:lombok:1.18.26'
  testAnnotationProcessor 'org.projectlombok:lombok:1.18.26'
```

I guess it's because I have:
```
  implementation 'org.projectlombok:lombok:1.18.26'
  annotationProcessor 'org.projectlombok:lombok:1.18.26'
```

After removal - test breaks.

**Comment by autonomousapps** [comment]
Thanks for the report. Do you have a minimal reproducer?

**Comment by autonomousapps** [comment]
I need more information than that. What does the source look like? If I added such dependencies to an empty project I would not be surprised to be told to remove them.

**Comment by autonomousapps** [comment]
Closing as nonreproducible.
