### ISSUE TITLE
Ability to display advice for only project dependencies

### ISSUE THREAD

**Issue by changusmc** [autonomousapps/dependency-analysis-gradle-plugin#911]
**Is your feature request related to a problem? Please describe.**

We would like to start enforcing `buildHealth` checks in CI, but we have a lot of errors to get through. Since there's no baseline feature, we'd like to start ignoring 3rd party dependencies for now. One way we could do that is to itemize every 3pp we have in all the different advice types, but that would not scale well and it would be very verbose. Additionally, our current project structure inherits a lot of dependencies from our convention plugin that isn't configurable at the moment.

**Describe the solution you'd like**

```
dependencyAnalysis {
    issues {
        all {
            ignoreThirdParty(true)
        }
    }
}

```
**Describe alternatives you've considered**

Bundling every 3rd party dependency and adding them for every advice type we use

**Additional context**

I was able to get my desired build health report with the code below, the remaining work would be to add an extension to the plugin. If you're okay with this approach, I can prepare a PR for it.

```
diff --git a/src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt b/src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
index 0de3c82a..23aa620e 100644
--- a/src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
+++ b/src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
@@ -26,6 +26,9 @@ internal class ProjectHealthConsoleReportBuilder(
     val processorAdvice = mutableSetOf<Advice>()
 
     dependencyAdvice.forEach { advice ->
+      if (advice.coordinates is ModuleCoordinates || advice.coordinates is FlatCoordinates) {
+        return@forEach
+      }
       if (advice.isRemove()) removeAdvice += advice
       if (advice.isAdd()) addAdvice += advice
       if (advice.isChange()) changeAdvice += advice

```

**Comment by autonomousapps** [comment]
Thanks for the suggestion! Will think about it.

**Comment by autonomousapps** [comment]
You said
> Since there's no baseline feature

would that be even more preferable? I've often thought about this as a useful feature to add.

**Comment by autonomousapps** [comment]
Baseline issue: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/876
