### ISSUE TITLE
Project.getConvention is deprecated and scheduled for removal in Gradle 9.0

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-gradle-plugin#915]
**Build scan link**

**Plugin version**

1.20.0 (latest

**Gradle version**

8.2-rc-2

**(Optional) Android Gradle Plugin (AGP) version**

N/A

**`reason` output for bugs relating to incorrect advice**

n/a

**Describe the bug**

<img width="831" alt="image" src="https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/assets/1361086/6e127be2-9b75-4fcc-b3f4-1149dc491d5b">

**To Reproduce**
1. Run a build using the plugin in Gradle 8.2 

**Expected behavior**

This API will need to be updated

**Additional context**

**Comment by autonomousapps** [comment]
This might be a duplicate. This plugin doesn't call the deprecated method. I think it's called by internal Gradle code when instantiating certain objects.

**Comment by Mahoney** [comment]
I'm seeing it at this stack:
```
	at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
	at com.autonomousapps.subplugin.ProjectPlugin$KotlinSources.<init>(ProjectExtensions.kt:109)
	at com.autonomousapps.subplugin.ProjectPlugin$configureKotlinJvmProject$1.execute(ProjectPlugin.kt:393)
```

I wonder if it's this:

> Also note that Plugins compiled with Gradle ⇐ 8.1 that make use of the Kotlin DSL functions [Project.the<T>()](https://docs.gradle.org/8.2/kotlin-dsl/gradle/org.gradle.kotlin.dsl/the.html), [Project.the(KClass)](https://docs.gradle.org/8.2/kotlin-dsl/gradle/org.gradle.kotlin.dsl/the.html) or [Project.configure<T> {}](https://docs.gradle.org/8.2/kotlin-dsl/gradle/org.gradle.kotlin.dsl/configure.html) will emit a deprecation warning when run on Gradle >= 8.2. To fix this these plugins should be recompiled with Gradle >= 8.2 or changed to access extensions directly using `extensions.getByType<T>()` instead.
https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#deprecated_access_to_conventions

I see that `Project.the` is used in [KotlinSources constructor](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/v1.20.0/src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt#L929-L930).

**Comment by autonomousapps** [comment]
Yes, I also see that in the stack, but it's just plugin code instantiating a Gradle object.

If upgrading to Gradle 8.2+ fixes the issue without breaking any of the current tests, that would be a fine resolution, and PRs are welcome.

**Comment by TWiStErRob** [comment]
Yeah, it simply needs to be recompiled against Kotlin DSL in Gradle 8.2 so the inline method body contains the fixes (ignore) for the convention deprecation, or migrate away from `.the()` to equivalents. [Source](https://github.com/gradle/gradle/issues/25206#issuecomment-1572186680).

**Comment by TWiStErRob** [comment]
I think that means this is fixed by https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/91433bf07783880dc5eb6b14003992efca7fade2

**Comment by autonomousapps** [comment]
does someone (e.g. @ZacSweers ) want to verify that the deprecation warning has disappeared? If so I will close this.

**Comment by Mahoney** [comment]
I don't see it running gradle 8.4, kotlin 1.9.10 and dependency-analysis 1.25.0

**Comment by autonomousapps** [comment]
I will optimistically close this then!
