### ISSUE TITLE
graph View test tasks do not allow self-loops in ProjectCoordinates 

### ISSUE THREAD

**Issue by kingargyle** [autonomousapps/dependency-analysis-gradle-plugin#941]
**Build scan link**

Unfortunately this is an internal application and link not available publicly 

**Plugin version*

1.19.0 and 1.20.0

**Gradle version**

7.6.1

**(Optional) Android Gradle Plugin (AGP) version**
7.4.1

**`reason` output for bugs relating to incorrect advice**

N/A

**Describe the bug**
We have a couple repos that this bug or issue occurs. When running project Health the test graphviews will report the self loop error. 

Unfortunately these are set up similar to the way the projects of similar size are configured using same agp and gradle versions. 

Looking for ways that I can help identify the actual cause as unfortunately these aren't public repos. 

**To Reproduce**
Run project Health task 

**Expected behavior**
Task shouldn't crash

**Additional context**

N/A

**Comment by kingargyle** [comment]
Following the faq for ignoring the tests from analysis at least let's me do the rest of the analysis. It would be nice though to have more details on why it gets into a recursive situation

**Comment by autonomousapps** [comment]
Thanks for the report. Unfortunately it's not actionable at the moment. I'll need at least a stacktrace. A build scan and reproducer would also be very useful.

**Comment by autonomousapps** [comment]
Closing as nonreproducible.
