### ISSUE TITLE
Kotlin Project exposing dependency via extension functions in `testFixtures` claims dependency unused

### ISSUE THREAD

**Issue by Nava2** [autonomousapps/dependency-analysis-gradle-plugin#942]
**Reproducing project**
https://github.com/Nava2/dependency-analysis-gradle-plugin-testfixtures-failure

**Build scan link**
https://scans.gradle.com/s/qu6lenwhzmwce

**Plugin version**
1.20.0, 1.21.0

**Gradle version**
7.5

**`reason` output for bugs relating to incorrect advice**
Library is used.

```
 $ ./gradlew reason --id "org.assertj:assertj-core:3.24.0"            [19:33:18]

> Task :reason

----------------------------------------
You asked about the dependency 'org.assertj:assertj-core:3.24.0'.
You have been advised to remove this dependency from 'testFixturesApi'.
----------------------------------------

There is no path from root project to org.assertj:assertj-core:3.24.0 for compileClasspath


There is no path from root project to org.assertj:assertj-core:3.24.0 for runtimeClasspath


Shortest path from root project to org.assertj:assertj-core:3.24.0 for testCompileClasspath:
:
\--- org.assertj:assertj-core:3.24.0

Shortest path from root project to org.assertj:assertj-core:3.24.0 for testRuntimeClasspath:
:
\--- org.assertj:assertj-core:3.24.0

Source: main
------------
(no usages)

Source: test
------------
(no usages)

BUILD SUCCESSFUL in 2s
31 actionable tasks: 1 executed, 30 up-to-date
```

**Describe the bug**
`testFixturesApi` is recommended to be removed, but is used.

**To Reproduce**
1. Run `./gradlew projectHealth` in project https://github.com/Nava2/dependency-analysis-gradle-plugin-testfixtures-failure

**Expected behavior**
Not deemed unused

**Comment by Nava2** [comment]
Confirmed still an issue on 1.21.0

**Comment by autonomousapps** [comment]
Thanks for the report.

**Comment by autonomousapps** [comment]
@Nava2 you gave me a reproducer, which puts you in the top 1% of people submitting issues, which is why I added this issue to the `next` milestone. You're good! Thanks for asking though.

If you're feeling spunky you could try to write a test case, but most people find those challenging because writing Gradle tests is not very straightforward. If that interests you, I could provide some pointers.

**Comment by autonomousapps** [comment]
I cannot reproduce this with the latest version, 1.24.0. Going to close, but feel free to reopen if you see it again.
