### ISSUE TITLE
buildHealth gives conflicting advice when using Kotlin 1.9

### ISSUE THREAD

**Issue by Vichy97** [autonomousapps/dependency-analysis-gradle-plugin#963]
**Plugin version**
1.22.0

**Gradle version**
8.3

**(Optional) Android Gradle Plugin (AGP) version**
8.3-alpha01

**`reason` output for bugs relating to incorrect advice**
```
Shortest path from :app to androidx.compose.foundation:foundation-android:1.5.1 for releaseUnitTestRuntimeClasspath:
:app
\--- androidx.compose.foundation:foundation:1.5.1
      \--- androidx.compose.foundation:foundation-android:1.5.1

Source: debug, main
-------------------
* Uses 2 classes: androidx.compose.foundation.BorderStroke, androidx.compose.foundation.DarkThemeKt (implies implementation).
* Provides 1 lint registry: androidx.compose.foundation.lint.FoundationIssueRegistry (implies implementation).

Source: release, main
---------------------
* Uses 2 classes: androidx.compose.foundation.BorderStroke, androidx.compose.foundation.DarkThemeKt (implies implementation).
* Provides 1 lint registry: androidx.compose.foundation.lint.FoundationIssueRegistry (implies implementation).

Source: debug, test
-------------------
* Provides 1 lint registry: androidx.compose.foundation.lint.FoundationIssueRegistry (implies testImplementation).
```

**Describe the bug**
Running `buildHealth` using kotlin 1.9 gives conflicting advice and it's not possible to correct. The only way to get this to pass is to ignore these dependencies. These same exact dependencies were working fine on kotlin 1.8.2

```
Advice for :app
Unused dependencies which should be removed:
  implementation("androidx.compose.foundation:foundation-layout:1.5.1")
  implementation("androidx.compose.foundation:foundation:1.5.1")
  implementation("androidx.compose.runtime:runtime:1.5.1")
  implementation("androidx.compose.ui:ui-graphics:1.5.1")
  implementation("androidx.compose.ui:ui-text:1.5.1")
  implementation("androidx.compose.ui:ui-unit:1.5.1")
  implementation("androidx.compose.ui:ui:1.5.1")
  implementation("androidx.lifecycle:lifecycle-common:2.6.1")

These transitive dependencies should be declared directly:
  implementation("androidx.compose.foundation:foundation-android:1.5.1")
  implementation("androidx.compose.foundation:foundation-layout-android:1.5.1")
  implementation("androidx.compose.runtime:runtime-android:1.5.1")
  implementation("androidx.compose.ui:ui-android:1.5.1")
  implementation("androidx.compose.ui:ui-graphics-android:1.5.1")
  implementation("androidx.compose.ui:ui-text-android:1.5.1")
  implementation("androidx.compose.ui:ui-unit-android:1.5.1")
  ```
  I have all these dependencies in my gradle.build for this module. Removing them will still tell me I am using them transitively.

**Comment by autonomousapps** [comment]
Thanks for the issue. Can you try version 1.24.0? And do you have a reproducer?

**Comment by Vichy97** [comment]
I can try version 1.24.0. I don't have a minimal reproducer, but I can try to make one.

**Comment by Vichy97** [comment]
@autonomousapps on 1.24.0 it is failing for a different but similar reason:
```
These transitive dependencies should be declared directly:
  implementation("androidx.compose.foundation:foundation-layout:1.5.1") { capabilities {
    requireCapability("androidx.compose.foundation:foundation-layout")
  }}
  implementation("androidx.compose.foundation:foundation:1.5.1") { capabilities {
    requireCapability("androidx.compose.foundation:foundation")
  }}
  implementation("androidx.compose.runtime:runtime:1.5.1") { capabilities {
    requireCapability("androidx.compose.runtime:runtime")
  }}
  implementation("androidx.compose.ui:ui-graphics:1.5.1") { capabilities {
    requireCapability("androidx.compose.ui:ui-graphics")
  }}
  implementation("androidx.compose.ui:ui-text:1.5.1") { capabilities {
    requireCapability("androidx.compose.ui:ui-text")
  }}
  implementation("androidx.compose.ui:ui-unit:1.5.1") { capabilities {
    requireCapability("androidx.compose.ui:ui-unit")
  }}
  implementation("androidx.compose.ui:ui:1.5.1") { capabilities {
    requireCapability("androidx.compose.ui:ui")
  }}
  ```
  
Again, I have all of these dependencies in my build.gradle (without the capabilites part). If I add the `capabilities` as suggested, the error remains the same.

**Comment by Vichy97** [comment]
https://github.com/Vichy97/Route-Search/pull/20 This isn't really a minimal repro project, but this is the repo I'm working in with the changes I made to upgrade to kotlin 1.9. What's also interesting is that it is now saying the lifecycle dependency is unused, but before upgrading to 1.24.0, it did not give me that warning.

**Comment by Vichy97** [comment]
Ok I realized that it was not conflicting, but it was suggesting the `-android` version of each of these dependencies. I also realized this has nothing to do with the kotlin upgrade, but happens when I upgrade compose. Maybe the classes being used moved in a newer version of compose? This issue might be able to just be closed, but I want to confirm that the error I saw on 1.24 still persists if I fix these dependencies.

**Comment by Vichy97** [comment]
Ok after a bit more testing on 1.24.0, it seems that I need both the android and non-android version of each dependency. For example I need both `implementation("androidx.compose.foundation:foundation-layout:1.5.1")` and `implementation("androidx.compose.foundation:foundation:1.5.1")` or I will get the warning 
```
 implementation("androidx.compose.foundation:foundation-layout:1.5.1") { capabilities {
    requireCapability("androidx.compose.foundation:foundation-layout")
  }}
  ```
I'm not sure if this is some weirdness with the latest version of compose or something wrong with this plugin, but at the version least the advice in 1.24 does not seem to line up with what is actually required to prevent this warning

**Comment by poliver** [comment]
Here's a minimal repro: https://github.com/poliver/DagpKmpRepro

**Comment by poliver** [comment]
I'm also seeing that both canonical and target (`-android`) deps are needed. If either is missing, DAGP will advise.

**Comment by jjohannes** [comment]
After some analysis, we have to unpack this a bit.

----

Firs looking at versions `1.22.0` and `1.23.0` which has no specific support for KMP dependencies (no #919). For this, the original advice is correct. If you change the _compose_ libraries in `libs.versions.toml` following the advice, the project still compiles buildHealth is green:

```
compose-foundation = { module = "androidx.compose.foundation:foundation-android" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout-android" }
compose-runtime = { module = "androidx.compose.runtime:runtime-android" }
compose-ui = { module = "androidx.compose.ui:ui-android" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics-android" }
compose-ui-text = { module = "androidx.compose.ui:ui-text-android" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview-android" }
compose-ui-unit = { module = "androidx.compose.ui:ui-unit-android" }
compose-material3 = { module = "androidx.compose.material3:material3-android", version = "1.2.0-alpha08" }
```
----

Now with version `1.24.0`, there is specific support for KMP dependencies (#919 is in) which, IIUC, should replace the need to define the `-android` variants and the reproducer project should be ok as it is. However, now you need to define **both** dependencies (e.g. `androidx.compose.foundation:foundation` AND `androidx.compose.foundation:foundation-android`) for _buildHealth_ to pass. This is clearly not how it should be. 

There was probably something missed in #919 – @ZacSweers / @autonomousapps could you have a look? 

(What is also weird is that the wrong advices contain a `requireCapability` part, maybe the `"org.jetbrains.kotlin.platform.type": "androidJvm"` attribute that we now track messes things up in an unexpected way)

**Comment by autonomousapps** [comment]
I'm currently investigating this and posting my notes here so that I don't forget where I am in the analysis. I should also write this up in a doc somewhere so that others can attempt, or even just for myself because the plugin is complex and it's easy to forget how to trace the analysis steps.

Here's roughly how it goes in this case:
1. User declares **androidx.compose.foundation:foundation**.
2. Artifact resolves to **androidx.compose.foundation:foundation-android:1.6.0-alpha06** with various attributes etc.
3. Explode jars (fka "all-declared-dependencies.json") creates an output at **androidx.compose.foundation:foundation-android:1.6.0-alpha06**.
4. Compute usages creates a trace report at **androidx.compose.foundation:foundation:1.6.0-alpha06**.
5. Compute advice creates a usage report at **androidx.compose.foundation:foundation:1.6.0-alpha06**.
6. We end up with a final advice at **androidx.compose.foundation:foundation:1.6.0-alpha06**.

The physical artifact and exploded jar both point to **-android** variant, but otherwise the reports all point to the **base** variant. Everything seems correct except for the final advice, which should simply not exist. So, investigate the **ComputeAdviceTask**. Why does it think this dependency is undeclared? Probably something to do with the complexity of the `Coordinates` representation, and maybe also that the `Declaration` itself is very simple and logically separate from the `Coordinates` concept.

Not strictly related, but the advice should _not_ include the `requireCapability` stuff when the capability is the _default_ capability (that is, when the capability matches the declaration).

**Comment by autonomousapps** [comment]
I've decided that the best thing to do to move forward is to [revert](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1032) https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/919. This means that Android KMP users (the majority of KMP users) will get advice like "remove foundation, add foundation-android"). We may take another look at that in the future. But for now, this is the most straightforward approach to restore some sanity to the various internal models and eliminate this much worse bug.
