### ISSUE TITLE
`reason` doesn't show the reasons of the asked dependency

### ISSUE THREAD

**Issue by BraisGabin** [autonomousapps/dependency-analysis-gradle-plugin#978]
**Plugin version**
1.24.0

**Gradle version**
8.3

**JDK version**
17

**(Optional) Android Gradle Plugin (AGP) version**
8.1.2

**Describe the bug**
When I run `./gradlew :asdf:reason --id androidx.room:room` I expect to see the reasons for `androidx.room:room` but the output I get starts with:

> `You asked about the dependency 'androidx.room:room-common:2.5.2'.`

I'm getting the reasons of `androidx.room:room-common` instead of `androidx.room:room`

**Expected behavior**
I expect to get the reason for the dependency I ask for.

**Context**
The problem could be even bigger because if I write `./gradlew :asdf:reason --id androidx` the output is:

> `You asked about the dependency 'androidx.activity:activity-ktx:1.7.2'.`

When I would expect the task `reason` to fail as `androidx` is clearly not a valid id.

**Comment by autonomousapps** [comment]
Thanks for the issue. I think this might be fixed on `main` already, but I'm not sure.

**Comment by autonomousapps** [comment]
This should now be fixed on main.
