### ISSUE TITLE
Plugin requires a lot of JVM metaspace

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-gradle-plugin#982]
**Build scan link**

**Plugin version**

1.24.0

**Gradle version**

8.3

**JDK version**

20

**(Optional) Android Gradle Plugin (AGP) version**

8.x (see on multiple versions)

**(Optional) `reason` output for bugs relating to incorrect advice**

**Describe the bug**

I see this log from gradle often during analysis

```
The Daemon will expire after the build after running out of JVM Metaspace.
The project memory settings are likely not configured or are configured to an insufficient value.
The daemon will restart for the next build, which may increase subsequent build times.
These settings can be adjusted by setting 'org.gradle.jvmargs' in 'gradle.properties'.
The currently configured max heap space is '16 GiB' and the configured max metaspace is '1 GiB'.
```

**To Reproduce**
1. Run dagp on a project of significant size

**Expected behavior**

**Additional context**

Presumably because of all the classloading. May be useful to doc somewhere recommending raising metaspace, as gradle's default is pretty puny

**Comment by autonomousapps** [comment]
Not sure if this is a bug, an enhancement, or something I can't do anything about thanks to more fundamental issues with Gradle.

Thanks for the issue. Do you think this is is something best documented in the readme or the wiki?

**Comment by autonomousapps** [comment]
https://github.com/autonomousapps/dependency-analysis-gradle-plugin/wiki/FAQ#the-daemon-will-expire-after-the-build-after-running-out-of-jvm-metaspace
