### ISSUE TITLE
Internal classes are not taken into account when using K2 compiler

### ISSUE THREAD

**Issue by Vichy97** [autonomousapps/dependency-analysis-gradle-plugin#984]
**Plugin version**
1.24.0

**Gradle version**
8.3

**Describe the bug**
```
module A:
class Bar { } 

Module B:
internal class Foo(bar: Bar) { }
```
In this example, the plugin will ask me to expose module A as `api` in the build file for module B when it should be `implementation` since the constructor for `Foo` is internal. If I turn off K2 compiler, this works as expected. I have quite a few internal classes and this behavior was consistent wherever I had internal classes. 

**Expected behavior**
Dependencies exposed through internal constructors or methods should be included via `implementation` not `api`

**Comment by autonomousapps** [comment]
Thanks for the issue. Could you please provide a reproducer?

**Comment by Vichy97** [comment]
@autonomousapps I attempted to repro with a minimal repro project and was able to for 1.24.0, but was unable to with the latest version 1.26.0. I think this has been fixed and can be closed
